### PR TITLE
Update ground segmentation part

### PR DESCRIPTION
**Pull request by LimHyungTae**
To Whom It May Concern:

Hello! thank you for this wonderful page and I'd like to do PR to update the `ground segmentation` sections.

In particular, I uploaded some renowned ground segmentation methods (over 100 stars)

Thank you for giving me the opportunity to contribute to this site :)

### CODE REVIEW

**Comment by LimHyungTae** [comment]
@horverno Thank you for your kind self-request, but is there another guy to check this PR? The procedure is stopped on the "1 pending reviewer"

**Comment by horverno** [comment]
> @horverno Thank you for your kind self-request, but is there another guy to check this PR? The procedure is stopped on the "1 pending reviewer" 

@LimHyungTae it is weekend you know 😅 i will review it next week

**Review by horverno — CHANGES_REQUESTED** [review]
Can you please also note that Patchwork++ also has ROS version? After that your pr will be merged, thanks!

**Comment by LimHyungTae** [comment]
Sorry for bothering you on the weekend! I revised it. Thank you Horváth :) ~~

**Comment by LimHyungTae** [comment]
P.S. I guess that it is more appropriate that your `urban_road_filter` method is below the ground segmentation, isn't it?

**Comment by horverno** [comment]
> Sorry for bothering you on the weekend! I revised it. Thank you Horváth :) ~~

No worries, thanks for this cool PR 👍

`urban_road_filter` has also similar purpose, but the goal is to extract drivable area not ground
I will consider a small reorganization in the future

**Pull request merged**
